### ISSUE TITLE
Agentx support

### ISSUE THREAD

**Issue by pythonxian** [sonic-net/sonic-quagga#28]
Hi All, 

Could anyone please share some insight on how to configure agentx, either on bgpd.conf or under the vtysh?

it seems that agentx is not accepted under the vtysh mode. Also, the bgpd daemon would stop initializing if i put agentx (as per doc) under the bgpd.conf.j2 & zebra.conf.j2. 

I have tried anything i know and nothing works. 

Please advise.

Thanks

**Comment by pavel-shirshov** [comment]
Hi,
If you still have this question: https://github.com/Azure/sonic-buildimage/pull/2981
Current FRR have agentx enabled for bgpd
